server:
  port: 80
spring:
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: localhost
      port: 8500
      service-name: ${spring.application.name}
  application:
    name: cloud-consumer-openfeign-order